language: shell
script: make test
branches:
  only:
    - master
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/generate-local-changelog/master/bin/generate-local-changelog) -u > CHANGELOG.md; fi
  - if [ "$TRAVIS_TAG" != "" ]; then bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/generate-local-changelog/master/bin/generate-local-changelog) > CHANGELOG.md; fi
  - git config user.email "$GITHUB_USER_EMAIL"
  - git config user.name "$GITHUB_USER_NAME"
  - git remote set-url origin "https://$GITHUB_TOKEN@github.com/neogeek/generate-local-changelog"
  - git add CHANGELOG.md
  - git commit -m "Updated CHANGELOG.md [skip ci]"
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then git push origin HEAD:"${TRAVIS_PULL_REQUEST_BRANCH}"; else git push origin HEAD:master; fi
