[package]
name = "generate-local-changelog"
version = "2.0.0"
edition = "2021"

[dependencies]
clap = "4.4.7"
git2 = "0.18.1"
regex = "1.10.2"
time = { version = "0.3.30", features = ["local-offset"] }
version-compare = "0.1.1"
