[package]
name = "generate-local-changelog"
version = "2.0.0"
edition = "2021"

[dependencies]
clap = "4.4.4"
git2 = "0.18.0"
regex = "1.9.5"
time = { version = "0.3.28", features = ["local-offset"] }
version-compare = "0.1.1"
