name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Configure rust
        run: rustup toolchain install stable

      - name: Run Check
        run: cargo check

      - name: Run Clippy
        run: cargo clippy

      - name: Run Tests
        run: cargo test
